jobs:
  setup-project:
    - create-webhook-if-not-present
    - curl -h Authorization: << pipeline.parameters.circleci_token >>
    - do-other-stuff
  report-job-status:
  upload-terraform-artifacts:
  build-gradle:
    - report-job-status:
    - proper-caching
    - build
  build-docker:
    - report-job-status:
    - aws/ecr build
  push-docker:
    - report-job-status:
    - aws/ecr push
  generate-techdocs:
    - report-job-status:
    - railyard/generate
  publish-techdocs:
    - report-job-status:
    - railyard/publish
  manual-deploy-to-test:
    - report-job-status:

workflows:
  build-and-deploy:
    when:
      not:
        equal: [ api, << pipeline.trigger_source >> ]
    jobs:
      - setup-project
      - terraform/validate
      - build-gradle
      - upload-terraform-artifacts
      - build-docker
      - push-docker
      - deployment/trigger-deployment
      - generate-techdocs
      - publish-techdocs

  manual-deploy-to-test:
    when:
      equal: [ api, << pipeline.trigger_source >> ]
      jobs:
        - setup-project
        - terraform/validate
        - build-gradle
        - upload-terraform-artifacts
        - build-docker
        - push-docker
        - manual-deploy-to-test