description: >
  This command echos "Hello World" using file inclusion.
# What will this command do?
# Descriptions should be short, simple, and clear.
parameters:
steps:
  - run:
      environment:

      name: Hello Greeting
      command: <<include(scripts/greet.sh)>>
