description: >
  This executor is using Docker, and accepts a tag as a parameter. If not supplied, it defaults to stable
docker:
  - image: 'cimg/base:<<parameters.tag>>'
parameters:
  tag:
    default: stable
    description: >
      Pick a specific cimg/node image variant (defaults to stable):
      https://hub.docker.com/r/cimg/node/tags
    type: string
